FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /src

COPY ["Bff.Api/Bff.Api.csproj", "Bff.Api/"]
COPY ["Bff.Core/Bff.Core.csproj", "Bff.Core/"]
RUN dotnet restore "Bff.Api/Bff.Api.csproj"

COPY . .
WORKDIR /src/Bff.Api
EXPOSE 8080
CMD ["dotnet", "watch", "run", "--no-launch-profile", "--urls", "http://0.0.0.0:8080"]
